version: 2
jobs:
  build:
    
    working_directory: ~/choice-player

    docker:
      - image: tgalopin/maven-javafx

    steps:
      - checkout

      - restore_cache:
          key: choice-player-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: choice-player-{{ checksum "pom.xml" }}
      
      - run: mvn package shade:shade
      
      - store_test_results:
          path: target/surefire-reports

      - run: for i in $(\ls -d target/*shaded.jar); do mv $i $(echo $i | sed 's/choice-player/ChoicePlayer/' | sed 's/\-shaded//'); done;
      
      - store_artifacts:
          path: target/ChoicePlayer-*.jar