version: 2
jobs:
  build:
    
    working_directory: ~/choice-player

    docker:
      - image: tgalopin/maven-javafx

    steps:
      - checkout

      - restore_cache:
          key: choice-player-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: choice-player-{{ checksum "pom.xml" }}
      
      - run: mvn package shade:shade -Pskip.some.tests
      
      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/choice-player-1.0.0.jar